---
dependency:
  name: {{ cookiecutter.dependency_name }}
  options:
    role-file: requirements.yml
driver:
  name: 'docker'
lint: |
  set -e
  {{ cookiecutter.lint_name }} .
  {{ cookiecutter.provisioner_lint_name }}
  {{ cookiecutter.verifier_lint_name }}
platforms:
  - name: 'test1-docker-oraclelinux7-{{ cookiecutter.role_name }}-${MOLECULE_USER:-$USER}'
    image: 'oraclelinux:7'
    pre_build_image: true
    privileged: '{{ cookiecutter.docker_privileged }}'
    groups:
      - '{{ cookiecutter.role_name }}'
    command: '/usr/sbin/init'
    tty: true
provisioner:
  name: ansible
  log: true
  playbooks:
    verify: ../resources/tests/verify.yml
scenario:
  name: 'test-docker'
verifier:
  name: {{ cookiecutter.verifier_name }}
