---
- name: Converge
  hosts: all
  # molecule converge is failed on Gathering Facts
  # https://github.com/ansible-community/molecule-docker/issues/197
  gather_facts: false
  roles:
    - role: 'ansible-role-{{ cookiecutter.role_name }}'
